# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_bundler_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install
      - save_bundler_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: yarn install
      - run: bundle exec jekyll doctor

  deploy:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    environment:
      CIRCLE_BRANCH: develop

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install
      - run: yarn install
      - run: git config --global user.email "ci-build@coopdevs.org"
      - run: git config --global user.name "CI"
      - add_ssh_keys:
          fingerprints:
            - "f6:8f:6b:93:bf:a3:a1:52:46:c6:2b:54:b6:5c:2e:23"
      - run: git config -l
      - run: ./deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
